### ISSUE TITLE
Plugin registers but seems to do nothing

### ISSUE THREAD

**Issue by systeminsightsbuild** [lithiumtech/elasticsearch-consul-discovery#10]
The plugin seems to get registered:

[2016-01-30 14:50:35,938][INFO ][plugins                  ] [ops-elk-2] loaded [consul-discovery], sites [hq, kopf]

But then nothing else. Certainly no cluster is formed.

Both es instances have services in consul (under the same) and are healthy.

My config looks like:

      discovery:
        type: consul
        consul:
          service-names: ["elasticsearch"]

What could I be missing?

**Comment by JigarJoshi** [comment]
Config should look like

```
discovery:
  consul:
    service-names:
    - elasticsearch
  type: consul
```

and make sure your `consul` service name is really `elasticsearch`

**Comment by systeminsightsbuild** [comment]
service-names:
    -elasticsearch 

is equivelant to 

  service-names: ["elasticsearch"]

in yaml.

But that was not my problem. My ansible config was not setting the entire config. My mistake. Fixed now.

What I am seeing now is lots of zen discovery errors due to connection refused on 9302. What does that mean in the context consul? Why does any zen discovery come into play when querying the local consul agent?

The stack traces have no 'org.elasticsearch.discovery.consul' in them. But I see that ConsulDiscovery extends ZenDiscovery. Is that kicking off some unecessary stuff?

**Comment by JigarJoshi** [comment]
Could you please post exception stacktrace ? also your ES config (around discovery) and how does your service look like in consul ?

**Comment by systeminsightsbuild** [comment]
I think the exceptions are just being logged at TRACE. From what I can tell, the plugin seems to working:

```
2016-01-31 02:59:07,626][DEBUG][discovery.consul         ] [ops-elk-1] 2 ms it took for discovery request
[2016-01-31 02:59:07,715][DEBUG][discovery.consul         ] [ops-elk-1] using consul based dynamic discovery nodes []
[2016-01-31 02:59:09,244][DEBUG][discovery.consul         ] [ops-elk-1] 0 ms it took for discovery request
[2016-01-31 02:59:09,244][DEBUG][discovery.consul         ] [ops-elk-1] using consul based dynamic discovery nodes []
[2016-01-31 02:59:10,746][DEBUG][discovery.consul         ] [ops-elk-1] 0 ms it took for discovery request
[2016-01-31 02:59:10,747][DEBUG][discovery.consul         ] [ops-elk-1] using consul based dynamic discovery nodes []
[2016-01-31 02:59:10,765][DEBUG][discovery.consul         ] [ops-elk-1] filtered ping responses: (filter_client[true], filter_data[false]) {none}
[2016-01-31 02:59:10,765][DEBUG][discovery.consul         ] [ops-elk-1] elected as master, waiting for incoming joins ([0] needed)
```

Let me bring back up the other node and see if the cluster forms.

BTW, do you configure 'discovery.zen.minimum_master_nodes' ?

**Comment by systeminsightsbuild** [comment]
So I seem to have a chicken and egg, maybe left over from my configuration pre cluster.

My consul health check uses

```esStatus="$(curl -XGET ${host}:${port}/_cluster/health | jq '.status')"```

But since a cluster has not been elected yet the service is always in a fail state. What are you using for consul health checks for the individual ES nodes?

**Comment by JigarJoshi** [comment]
I have healthcheck setup based on port `9300`'s availability

**Comment by systeminsightsbuild** [comment]
I am only running 2 nodes. If I set discovery.zen.minimum_master_nodes:1 then each node becomes master. If I set it two, then neither becomes master.

My port for the elasticsearch consul service is 9200. Does it need to be 9300?

**Comment by JigarJoshi** [comment]
http port is `9200`, but the internal communication port is `9300`, so I treat ES node healthy if it listens on 9300 (which **doesn**'t mean ES node is healthy but for DNS point of view service is running)

**Comment by systeminsightsbuild** [comment]
Hmm, so that is how I am currently configured.

Should I expect the es nodes to be in this list?

```[2016-01-31 04:15:18,936][DEBUG][discovery.consul         ] [ops-elk-2] using consul based dynamic discovery nodes []```

**Comment by JigarJoshi** [comment]
Yes you should see them here, what is the registered consul service name ?

could you please make sure your service name is `elasticsearch` ?

    $curl http://localhost:8500//v1/catalog/services

and

    $curl http://localhost:8500/v1/health/service/elasticsearch

what does this return ?

**Comment by systeminsightsbuild** [comment]
The ```consul-cli health-service elasticsearch``` above is pretty the same as ```curl http://localhost:8500/v1/health/service/elasticsearch```.

But it is the service name that the plugin is seeing. I forked and extended the logging. 

```[2016-01-31 04:30:35,135][TRACE][discovery.consul         ] [ops-elk-1] starting discovery request: consulServiceNames=[]```

Maybe elasticsearch does not us a standard yaml parser... I am using ansible to deploy with lineinfile to update the elasticsearch.yml. I may have to change that. A bit more debugging and I should be there.

thanks!

**Comment by JigarJoshi** [comment]
cool, good catch

**Comment by systeminsightsbuild** [comment]
Of course it was user error: ```discover.consul.service-names : ['elasticsearch']``` instead of ```discovery.consul.service-names : ['elasticsearch']```.

Now I see the nodes ```[ops-elk-1] discovered 2 nodes```.

But still no cluster. I get 503's from hq and kopf. But curl seems to work.

```
[barry@ops-elk-1]/var/log/elasticsearch❯ curl -XGET 'http://localhost:9200'
{
  "name" : "ops-elk-1",
  "cluster_name" : "ops",
  "version" : {
    "number" : "2.1.1",
    "build_hash" : "40e2c53a6b6c2972b3d13846e450e66f4375bd71",
    "build_timestamp" : "2015-12-15T13:05:55Z",
    "build_snapshot" : false,
    "lucene_version" : "5.3.1"
  },
  "tagline" : "You Know, for Search"
}
```

I am still using ```discovery.zen.minimum_master_nodes: 2```. Will try with 1 now...

**Comment by systeminsightsbuild** [comment]
Looks like zen is trying to use 9200

```[2016-01-31 04:52:37,510][TRACE][discovery.zen.ping.unicast] [ops-elk-1] [61] sending to {#zen_unicast_371_#consul-10.0.196.5:9200#}{10.0.196.5}{10.0.196.5:9200}```

**Comment by JigarJoshi** [comment]
because your service is registered over 9200 at consul

**Comment by systeminsightsbuild** [comment]
Ok, I got a cluster!

Here's the final config for reference:

elasticsearch.yml
```
iscovery.type : consul
discovery.consul.service-names : ['elasticsearch-node']
discovery.zen.minimum_master_nodes: 2
```

I defined two consul services, one for the nodes in the cluster on 9300 and one for clients on 9200 (in ansible'ly, but should be understandable):

```
    - role: consul
      consul_services:
        - name: elasticsearch-node
          tags: [ops, elk]
          address: "{{host_ip_address}}"
          port: 9300
          checks:
            - name: "elasticsearch-node"
              tcp: "localhost:9300"
              interval: "10s"
              timeout: "3s"
        - name: elasticsearch
          tags: [ops, elk]
          address: "{{host_ip_address}}"
          port: "{{elasticsearch_http_port | int}}"
          checks:
            - script: "{{elasticsearch_health_check_dir}}/es-health-check.sh"
              interval: 30s
```

**Comment by JigarJoshi** [comment]
:+1:

**Comment by systeminsightsbuild** [comment]
Thanks very much!
