### ISSUE TITLE
Is the repo still alive ?

### ISSUE THREAD

**Issue by vvanholl** [lithiumtech/elasticsearch-consul-discovery#16]
Hi,

Since many months, I don't see any new commit or PR merged. 
Do you continue to maintain it ?

**Comment by bdharrington7** [comment]
Hey @vvanholl sorry for the lack of action here, we'll try to take a look at the PRs in the coming weeks.

**Comment by bdharrington7** [comment]
@mattayres @JigarJoshi @srinikalyanaraman Since it looks like lithium is keeping up with the ES updates maybe this repo should be handed over to someone else?

**Comment by vvanholl** [comment]
@bdharrington7 @mattayres @JigarJoshi @srinikalyanaraman If Lithium has no time for that I could be interested in

**Comment by anuriq** [comment]
i vote for vvanholl

**Comment by siepkes** [comment]
For anyone looking in this thread; An actively maintained fork (by @vvanholl ) is here: https://github.com/vvanholl/elasticsearch-consul-discovery

Thanks @JigarJoshi for all your work on this great plugin!
