### ISSUE TITLE
ES Version 2.x

### ISSUE THREAD

**Issue by zohararad** [lithiumtech/elasticsearch-consul-discovery#3]
Looks like a great plugin! Would love to use it, but ideally with latest ES v2.0. Are you planning support for ES v2.x anytime soon?

**Comment by JigarJoshi** [comment]
Thanks! - I will make it ES 2.0 compatible

**Comment by zohararad** [comment]
Wow! thanks for the quick reply. Would love to hear from you once you did.

**Comment by frutik** [comment]
Any news?

**Comment by JigarJoshi** [comment]
vvanholl has created a PR https://github.com/lithiumtech/elasticsearch-consul-discovery/pull/5 for this already, Thanks for that, I will verify and merge PR soon

**Comment by zohararad** [comment]
Great. thanks for the update!

**Comment by JigarJoshi** [comment]
PR# 5 is merged

**Comment by zohararad** [comment]
Thanks a lot :+1:
