### ISSUE TITLE
Install?

### ISSUE THREAD

**Issue by systeminsightsbuild** [lithiumtech/elasticsearch-consul-discovery#9]
How is this installed? Do I need to build it locally and push the package somewhere that the plugin install will find? Is it already installed on elastic.com somewhere?

**Comment by JigarJoshi** [comment]
1. Clone source code
2. run `mvn clean install` on it (you need maven && JDK 8 for it) 
3. grab package from `target/releases`
4. run `$ES_HOME/bin/plugin install /path/to/elasticsearch-consul-discovery-$version.zip`

to install this plugin on that specific node of your ES

I will put it in README.md and see if there is a better way to distribute binary

**Comment by bsvingen** [comment]
https://github.com/lithiumtech/elasticsearch-consul-discovery/pull/6 should also help with this.

**Comment by systeminsightsbuild** [comment]
Thanks @JigarJoshi, that's what I did. It might be nice to create releases in this project so they can be installed directly by $ES/bin/plugin.

@bsvingen, would an rpm allow for installing via the es bin/puglin?

**Comment by systeminsightsbuild** [comment]
(Whoops, didn't mean to close.  But my question is answered if you want it closed.)

**Comment by bsvingen** [comment]
@systeminsightsbuild: The RPM can be placed in a yum repo, and then you can use "yum install" to get the ZIP installed - it means that you avoid having to manually copy the ZIP. Ideally we should set up a public yum repo, and have Travis (or similar) deploy it there automatically. We could also have the RPM automatically register itself with Elasticsearch, but I'm not sure if that's what we want to happen.

**Comment by cwc** [comment]
I'm not really familiar with how ES plugins 'work', but I've seen plugins that can be installed just by passing their GitHub signature to `plugin install`, like Kopf: https://github.com/lmenezes/elasticsearch-kopf/blob/master/README.md#installing-on-an-elasticsearch-instance

Would it be possible to support this installation method?

**Comment by JigarJoshi** [comment]
This is Java plugin it cannot be installed like Site plugin, it needs the binary built from source 

https://www.elastic.co/guide/en/elasticsearch/plugins/2.2/intro.html

This issue will take care of installing it via RPM as @bsvingen has provided PR https://github.com/lithiumtech/elasticsearch-consul-discovery/pull/6
